version: "3.8"

services:
  generator:
    build:
      context: .
      dockerfile: ./internal/Dockerfile
    image: generator:latest
    working_dir: /root
    command: ["/root/generator"]
    volumes:
      - ".:/app"
    profiles:
      - manual

  database:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=casino
      - POSTGRES_PASSWORD=casino
    volumes:
      - "./db:/db"
  
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   # AMQP protocol port
      - "15672:15672" # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  plData:
    build:
      context: .
      dockerfile: ./playerData/Dockerfile
    image: pldata:latest
    working_dir: /root
    command: ["/root/playerData"]
    environment:
      - MQ_CONNECTION_STRING=amqp://user:1234567@rabbitmq:5672/
      - PSQL_USER=casino
      - PSQL_PASSWORD=casino
      - PSQL_HOST=database
      - PSQL_DB=casino
