// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: players.sql

package db

import (
	"context"
)

const getPlayerById = `-- name: GetPlayerById :one
SELECT id, email, last_signed_in_at FROM players WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPlayerById(ctx context.Context, id int64) (Player, error) {
	row := q.db.QueryRowContext(ctx, getPlayerById, id)
	var i Player
	err := row.Scan(&i.ID, &i.Email, &i.LastSignedInAt)
	return i, err
}
